#!/usr/bin/env bash
# Rohomieo one-shot setup — WSL, native Linux, or Git Bash on Windows.
# For native Windows host capture, also run: powershell -ExecutionPolicy Bypass -File scripts/setup-windows.ps1
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}==>${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${RED}!${NC} $*"; }

IS_WSL=false
IS_LINUX=false
if grep -qi microsoft /proc/version 2>/dev/null; then
  IS_WSL=true
elif [[ "$(uname -s)" == "Linux" ]]; then
  IS_LINUX=true
fi

MODE="${ROHOMIEO_SETUP_MODE:-auto}"
if [[ "$MODE" == "auto" ]]; then
  if $IS_WSL; then MODE=wsl; elif [[ "$(uname -s)" == MINGW* ]] || [[ "$(uname -s)" == MSYS* ]]; then MODE=gitbash; else MODE=linux; fi
fi

info "Rohomieo setup (mode=$MODE, root=$ROOT)"

# ── OS packages ──────────────────────────────────────────────────────────────
install_apt_deps() {
  if ! command -v apt-get &>/dev/null; then
    warn "apt-get not found — install X11/xcb/xdo dev packages manually"
    return
  fi
  info "Installing apt packages (sudo)..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    build-essential pkg-config curl git ca-certificates \
    libx11-dev libxcb1-dev libxcb-shm0-dev libxcb-randr0-dev libxdo-dev \
    libssl-dev openssl \
    nodejs npm \
    2>/dev/null || sudo apt-get install -y \
    build-essential pkg-config curl git ca-certificates \
    libx11-dev libxcb1-dev libxcb-shm0-dev libxcb-randr0-dev libxdo-dev \
    libssl-dev openssl nodejs npm
  ok "apt packages"
}

# ── Rust ─────────────────────────────────────────────────────────────────────
install_rust() {
  if command -v cargo &>/dev/null; then
    ok "Rust already installed ($(rustc --version))"
    return
  fi
  info "Installing Rust via rustup..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  # shellcheck source=/dev/null
  source "$HOME/.cargo/env"
  ok "Rust installed"
}

ensure_cargo_path() {
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/.cargo/env"
  fi
}

# ── Node / web ─────────────────────────────────────────────────────────────────
build_web() {
  info "Building web PWA..."
  (cd "$ROOT/web" && npm ci && npm run build)
  ok "web/dist ready"
}

# ── Rust workspace ───────────────────────────────────────────────────────────
build_rust() {
  ensure_cargo_path
  info "Building Rust workspace (release)..."
  cargo build --release -p rohomieo-signaling
  if $IS_WSL; then
    warn "WSL: Linux host may not capture your Windows desktop — use Windows host (see below)"
    cargo build --release -p rohomieo-host 2>/dev/null || warn "host build skipped (missing display/libs)"
  else
    cargo build --release -p rohomieo-host
  fi
  ok "Rust binaries in target/release/"
}

# ── TLS dev cert ─────────────────────────────────────────────────────────────
gen_certs() {
  if [[ -f "$ROOT/infra/certs/cert.pem" ]]; then
    ok "TLS certs already exist"
    return
  fi
  if command -v openssl &>/dev/null; then
    info "Generating dev TLS cert..."
    bash "$ROOT/scripts/gen-dev-cert.sh"
    ok "infra/certs/"
  fi
}

# ── Config + bin stubs ───────────────────────────────────────────────────────
write_config() {
  mkdir -p "$ROOT/.local/bin" "$ROOT/var/log"
  local win_ip=""
  if $IS_WSL && command -v ip &>/dev/null; then
    win_ip=$(ip route show | awk '/default/ {print $3; exit}')
  fi
  cat >"$ROOT/.env.rohomieo" <<EOF
# Generated by setup.sh — source before running: source .env.rohomieo
export ROHOMIEO_ROOT="$ROOT"
export ROHOMIEO_BIND="${ROHOMIEO_BIND:-0.0.0.0:8443}"
export ROHOMIEO_SIGNALING_URL="${ROHOMIEO_SIGNALING_URL:-ws://127.0.0.1:8443/ws}"
export ROHOMIEO_WEB_ROOT="$ROOT/web/dist"
export ROHOMIEO_CERT="$ROOT/infra/certs/cert.pem"
export ROHOMIEO_KEY="$ROOT/infra/certs/key.pem"
export ROHOMIEO_WSL_WINDOWS_IP="${win_ip:-}"
EOF
  ok "Wrote .env.rohomieo"

  cat >"$ROOT/.local/bin/rohomieo-signaling" <<'WRAP'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$ROOT/.env.rohomieo" ]] && source "$ROOT/.env.rohomieo"
exec "$ROOT/target/release/rohomieo-signaling" \
  --bind "${ROHOMIEO_BIND}" \
  --web-root "${ROHOMIEO_WEB_ROOT}" \
  ${ROHOMIEO_CERT:+--cert "$ROHOMIEO_CERT"} \
  ${ROHOMIEO_KEY:+--key "$ROHOMIEO_KEY"} \
  "$@"
WRAP
  cat >"$ROOT/.local/bin/rohomieo-host" <<'WRAP'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$ROOT/.env.rohomieo" ]] && source "$ROOT/.env.rohomieo"
exec "$ROOT/target/release/rohomieo-host" \
  --signaling "${ROHOMIEO_SIGNALING_URL}" \
  "$@"
WRAP
  chmod +x "$ROOT/.local/bin/rohomieo-signaling" "$ROOT/.local/bin/rohomieo-host"
  ok "Wrappers in .local/bin/"
}

install_systemd_user() {
  if ! command -v systemctl &>/dev/null; then
    return
  fi
  mkdir -p "$HOME/.config/systemd/user"
  local bin="$ROOT/.local/bin"
  sed "s|@ROOT@|$ROOT|g; s|@BIN@|$bin|g" "$ROOT/infra/systemd/rohomieo-signaling.service.in" \
    >"$HOME/.config/systemd/user/rohomieo-signaling.service"
  systemctl --user daemon-reload
  systemctl --user enable rohomieo-signaling.service 2>/dev/null || true
  ok "systemd user service: rohomieo-signaling (start: systemctl --user start rohomieo-signaling)"
}

invoke_windows_setup() {
  local ps1="$ROOT/scripts/setup-windows.ps1"
  if [[ ! -f "$ps1" ]]; then return; fi
  local win_ps=""
  if command -v powershell.exe &>/dev/null; then
    win_ps="powershell.exe"
  elif command -v pwsh.exe &>/dev/null; then
    win_ps="pwsh.exe"
  fi
  if [[ -z "$win_ps" ]]; then
    warn "PowerShell not found — run manually on Windows:"
    warn "  powershell -ExecutionPolicy Bypass -File scripts\\setup-windows.ps1"
    return
  fi
  info "Running Windows setup via $win_ps (host agent for desktop capture)..."
  "$win_ps" -NoProfile -ExecutionPolicy Bypass -File "$(wslpath -w "$ps1")" -RepoRoot "$(wslpath -w "$ROOT")" || \
    warn "Windows setup failed — run setup-windows.ps1 from an elevated PowerShell on Windows"
}

# ── Main flow ──────────────────────────────────────────────────────────────────
case "$MODE" in
  wsl)
    install_apt_deps
    install_rust
    ensure_cargo_path
    gen_certs
    build_web
    build_rust
    write_config
    install_systemd_user
    invoke_windows_setup
    ;;
  linux)
    install_apt_deps
    install_rust
    ensure_cargo_path
    gen_certs
    build_web
    build_rust
    write_config
    install_systemd_user
    ;;
  gitbash)
    warn "Git Bash: run scripts/setup-windows.ps1 in PowerShell for full Windows setup"
    install_rust
    ensure_cargo_path
    build_web
    build_rust
    write_config
    ;;
  *)
    echo "Usage: ROHOMIEO_SETUP_MODE=auto|wsl|linux|gitbash $0"
    exit 1
    ;;
esac

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Rohomieo setup complete${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "  source $ROOT/.env.rohomieo"
echo "  $ROOT/.local/bin/rohomieo-signaling    # signaling + web UI"
echo "  $ROOT/.local/bin/rohomieo-host         # screen host (native OS)"
echo ""
if $IS_WSL; then
  echo "  WSL tip: signaling in WSL, host on Windows for your real desktop."
  echo "  After Windows setup: scripts\\start-windows-host.ps1"
  echo "  From phone/LAN use Windows IP (not WSL IP) unless port-forwarded."
  win_ip=$(grep ROHOMIEO_WSL_WINDOWS_IP "$ROOT/.env.rohomieo" 2>/dev/null | cut -d= -f2- | tr -d '"')
  [[ -n "$win_ip" ]] && echo "  Windows host IP (gateway): $win_ip"
fi
echo ""
echo "  Quick test: ./scripts/dev.sh"
echo "  Docs:       ./infra/wireguard/README.md"
echo ""
