# shellcheck shell=bash
# Shared helpers for setup-linux.sh, setup-wsl.sh, setup-macos.sh
# Source from repo scripts: source "$(dirname "$0")/lib/setup-common.sh"

[[ -n "${ROHOMIEO_SETUP_COMMON_LOADED:-}" ]] && return 0
ROHOMIEO_SETUP_COMMON_LOADED=1

: "${ROHOMIEO_ROOT:?ROHOMIEO_ROOT must be set}"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

setup_info()  { echo -e "${CYAN}==>${NC} $*"; }
setup_ok()    { echo -e "${GREEN}ok${NC} $*"; }
setup_warn()  { echo -e "${YELLOW}!${NC} $*"; }
setup_err()   { echo -e "${RED}ERROR:${NC} $*" >&2; }

setup_detect_platform() {
  IS_WSL=false
  IS_LINUX=false
  IS_MACOS=false
  case "$(uname -s)" in
    Darwin) IS_MACOS=true ;;
    Linux)
      IS_LINUX=true
      grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=true
      ;;
  esac
}

setup_ensure_lf() {
  # Fix CRLF if repo was checked out on Windows
  local f
  for f in "$ROHOMIEO_ROOT"/setup.sh "$ROHOMIEO_ROOT"/scripts/*.sh; do
    [[ -f "$f" ]] && sed -i 's/\r$//' "$f" 2>/dev/null || true
  done
}

setup_install_rust() {
  if command -v cargo &>/dev/null; then
    setup_ok "Rust $(rustc --version)"
    return
  fi
  setup_info "Installing Rust (rustup)..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  setup_ok "Rust installed"
}

setup_source_cargo() {
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/.cargo/env"
  fi
}

setup_install_node() {
  if command -v node &>/dev/null && command -v npm &>/dev/null; then
    setup_ok "Node $(node --version)"
    return
  fi
  setup_warn "Node/npm not found — install Node 18+ or re-run platform setup"
}

setup_build_web() {
  setup_info "Building web PWA..."
  (cd "$ROHOMIEO_ROOT/web" && npm ci && npm run build)
  setup_ok "web/dist"
}

setup_gen_certs() {
  if [[ -f "$ROHOMIEO_ROOT/infra/certs/cert.pem" ]]; then
    setup_ok "TLS certs exist"
    return
  fi
  if command -v openssl &>/dev/null; then
    setup_info "Generating dev TLS cert..."
    bash "$ROHOMIEO_ROOT/scripts/gen-dev-cert.sh"
    setup_ok "infra/certs/"
  else
    setup_warn "openssl missing — skip TLS (HTTP only)"
  fi
}

setup_build_rust() {
  local build_host="${1:-true}"
  setup_source_cargo
  cd "$ROHOMIEO_ROOT"
  setup_info "Building rohomieo-signaling (release)..."
  cargo build --release -p rohomieo-signaling
  if [[ "$build_host" == "true" ]]; then
    setup_info "Building rohomieo-host (release)..."
    cargo build --release -p rohomieo-host
  else
    setup_warn "Skipping rohomieo-host on this platform step (use Windows host on WSL)"
  fi
  setup_ok "target/release/"
}

setup_write_env() {
  local extra_env="${1:-}"
  mkdir -p "$ROHOMIEO_ROOT/.local/bin" "$ROHOMIEO_ROOT/var/log"
  local win_ip=""
  if [[ "${ROHOMIEO_PLATFORM:-}" == "wsl" ]] && command -v ip &>/dev/null; then
    win_ip=$(ip route show 2>/dev/null | awk '/default/ {print $3; exit}')
  fi
  cat >"$ROHOMIEO_ROOT/.env.rohomieo" <<EOF
# Generated by Rohomieo setup — source: source .env.rohomieo
export ROHOMIEO_ROOT="$ROHOMIEO_ROOT"
export ROHOMIEO_PLATFORM="${ROHOMIEO_PLATFORM:-linux}"
export ROHOMIEO_BIND="${ROHOMIEO_BIND:-0.0.0.0:8443}"
export ROHOMIEO_SIGNALING_URL="${ROHOMIEO_SIGNALING_URL:-ws://127.0.0.1:8443/ws}"
export ROHOMIEO_WEB_ROOT="$ROHOMIEO_ROOT/web/dist"
export ROHOMIEO_CERT="$ROHOMIEO_ROOT/infra/certs/cert.pem"
export ROHOMIEO_KEY="$ROHOMIEO_ROOT/infra/certs/key.pem"
export ROHOMIEO_WSL_WINDOWS_IP="${win_ip:-}"
${extra_env}
EOF
  setup_ok ".env.rohomieo"
}

setup_write_wrappers() {
  cat >"$ROHOMIEO_ROOT/.local/bin/rohomieo-signaling" <<'WRAP'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$ROOT/.env.rohomieo" ]] && source "$ROOT/.env.rohomieo"
ARGS=(--bind "${ROHOMIEO_BIND}" --web-root "${ROHOMIEO_WEB_ROOT}")
[[ -f "${ROHOMIEO_CERT:-}" && -f "${ROHOMIEO_KEY:-}" ]] && ARGS+=(--cert "$ROHOMIEO_CERT" --key "$ROHOMIEO_KEY")
exec "$ROOT/target/release/rohomieo-signaling" "${ARGS[@]}" "$@"
WRAP

  cat >"$ROHOMIEO_ROOT/.local/bin/rohomieo-host" <<'WRAP'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$ROOT/.env.rohomieo" ]] && source "$ROOT/.env.rohomieo"
exec "$ROOT/target/release/rohomieo-host" --signaling "${ROHOMIEO_SIGNALING_URL}" "$@"
WRAP

  chmod +x "$ROHOMIEO_ROOT/.local/bin/rohomieo-signaling" "$ROHOMIEO_ROOT/.local/bin/rohomieo-host"
  setup_ok "wrappers .local/bin/rohomieo-{signaling,host}"
}

setup_install_systemd_user() {
  command -v systemctl &>/dev/null || return 0
  [[ -d /run/systemd/system ]] || return 0
  mkdir -p "$HOME/.config/systemd/user"
  sed "s|@ROOT@|$ROHOMIEO_ROOT|g; s|@BIN@|$ROHOMIEO_ROOT/.local/bin|g" \
    "$ROHOMIEO_ROOT/infra/systemd/rohomieo-signaling.service.in" \
    >"$HOME/.config/systemd/user/rohomieo-signaling.service"
  systemctl --user daemon-reload 2>/dev/null || true
  systemctl --user enable rohomieo-signaling.service 2>/dev/null || true
  setup_ok "systemd user unit rohomieo-signaling (systemctl --user start rohomieo-signaling)"
}

setup_install_launchd_user() {
  [[ "$(uname -s)" == "Darwin" ]] || return 0
  local plist="$HOME/Library/LaunchAgents/com.rohomieo.signaling.plist"
  mkdir -p "$HOME/Library/LaunchAgents"
  cat >"$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.rohomieo.signaling</string>
  <key>ProgramArguments</key>
  <array>
    <string>$ROHOMIEO_ROOT/.local/bin/rohomieo-signaling</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$ROHOMIEO_ROOT/var/log/signaling.log</string>
  <key>StandardErrorPath</key><string>$ROHOMIEO_ROOT/var/log/signaling.err</string>
</dict></plist>
EOF
  setup_ok "launchd plist com.rohomieo.signaling"
  setup_warn "Load with: launchctl load $plist"
}

setup_invoke_windows() {
  local ps1="$ROHOMIEO_ROOT/scripts/setup-windows.ps1"
  [[ -f "$ps1" ]] || return 0
  local win_ps=""
  command -v powershell.exe &>/dev/null && win_ps="powershell.exe"
  command -v pwsh.exe &>/dev/null && [[ -z "$win_ps" ]] && win_ps="pwsh.exe"
  if [[ -z "$win_ps" ]]; then
    setup_warn "Run on Windows: powershell -File scripts\\setup-windows.ps1"
    return 0
  fi
  setup_info "Windows companion setup (host.exe + MSVC build)..."
  local win_script win_root
  win_script=$(wslpath -w "$ps1" 2>/dev/null) || win_script="$ps1"
  win_root=$(wslpath -w "$ROHOMIEO_ROOT" 2>/dev/null) || win_root="$ROHOMIEO_ROOT"
  if "$win_ps" -NoProfile -ExecutionPolicy Bypass -File "$win_script" -RepoRoot "$win_root"; then
    setup_ok "Windows setup finished"
  else
    setup_warn "Windows setup failed — install VS Build Tools, then run setup-windows.ps1"
  fi
}

setup_print_footer() {
  local platform="${1:-linux}"
  echo ""
  echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Rohomieo setup complete ($platform)${NC}"
  echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
  echo ""
  echo "  source $ROHOMIEO_ROOT/.env.rohomieo"
  case "$platform" in
    wsl)
      echo "  ./scripts/start-wsl.sh          # signaling in WSL"
      echo "  ./scripts/start-windows-host.ps1  # host on Windows (PowerShell)"
      ;;
    macos)
      echo "  ./scripts/start-macos.sh"
      echo "  Grant Screen Recording + Accessibility for rohomieo-host in System Settings"
      ;;
    linux)
      echo "  ./scripts/start-linux.sh"
      ;;
  esac
  echo "  Browser: http://127.0.0.1:8443"
  echo "  Windows: scripts\\start-windows-host.ps1"
  echo ""
}
