#!/usr/bin/env bash
# One command to run Rohomieo: ./scripts/run.sh [--local|--global]
# Auto-detects platform (Linux / WSL / macOS), starts signaling + (optional TURN)
# + host as background children of this script, and tears them down on Ctrl-C.
#
# Reachability:
#   --local   (default) same Wi‑Fi / LAN — join URL uses LAN IP, no UPnP/TURN
#   --global  internet — public IP + TURN + UPnP so a phone can open the URL anywhere
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib-platform.sh"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib-upnp.sh"

usage() {
  cat <<EOF
usage: $0 [--local|--global]

  --local   LAN only (default). Join URL uses LAN IP. No UPnP / TURN.
  --global  Internet. Public IP + TURN + UPnP so a phone can open the URL
            from anywhere (port-forward TCP 8443 + UDP/TCP 3478 if UPnP fails).

Platform is auto-detected (linux / wsl / macos).
EOF
}

MODE="local"
for arg in "$@"; do
  case "$arg" in
    --local) MODE="local" ;;
    --global) MODE="global" ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "unknown argument: $arg" >&2
      usage >&2
      exit 1
      ;;
  esac
done

PLATFORM="$(rohomieo_detect_platform)"
echo "==> platform: $PLATFORM · mode: $MODE"

export PATH="$(rohomieo_tool_path "${HOME:-}")${PATH:+:$PATH}"

[[ -f .env.rohomieo ]] || {
  mkdir -p var/log var/run .local/bin
  cat >.env.rohomieo <<EOF
# Generated by scripts/run.sh — safe to edit
export ROHOMIEO_ROOT="$ROOT"
export ROHOMIEO_BIND="0.0.0.0:8443"
export ROHOMIEO_SIGNALING_URL="wss://127.0.0.1:8443/ws"
export ROHOMIEO_WEB_ROOT="$ROOT/web/dist"
export ROHOMIEO_CERT="$ROOT/infra/certs/cert.pem"
export ROHOMIEO_KEY="$ROOT/infra/certs/key.pem"
EOF
}
# shellcheck disable=SC1091
source .env.rohomieo

# Reachability overrides — must win over .env.rohomieo for this run.
export ROHOMIEO_MODE="$MODE"
PORT="${ROHOMIEO_BIND##*:}"
PORT="${PORT:-8443}"
SCHEME="https"
[[ -f "${ROHOMIEO_CERT:-}" && -f "${ROHOMIEO_KEY:-}" ]] || SCHEME="http"
WS_SCHEME="wss"
[[ "$SCHEME" == "http" ]] && WS_SCHEME="ws"

ensure_turn_creds() {
  if [[ -n "${ROHOMIEO_TURN_USER:-}" && -n "${ROHOMIEO_TURN_PASS:-}" ]]; then
    return 0
  fi
  ROHOMIEO_TURN_USER="rh$(head -c 4 /dev/urandom | xxd -p)"
  ROHOMIEO_TURN_PASS="$(head -c 16 /dev/urandom | xxd -p)"
  {
    echo "ROHOMIEO_TURN_USER=$ROHOMIEO_TURN_USER"
    echo "ROHOMIEO_TURN_PASS=$ROHOMIEO_TURN_PASS"
  } >> .env.rohomieo
  export ROHOMIEO_TURN_USER ROHOMIEO_TURN_PASS
  echo "==> generated TURN credentials, saved to .env.rohomieo"
}

# Fixed session/PIN for this run so we can print the web-UI invite in this terminal.
export ROHOMIEO_SESSION="${ROHOMIEO_SESSION:-$(python3 -c 'import uuid; print(uuid.uuid4())')}"
export ROHOMIEO_PIN="${ROHOMIEO_PIN:-$(python3 -c 'import random; print(f"{random.randint(100000,999999)}")')}"

build_join_url() {
  # Builds https://…:8443/?s=&p=&auto=1… pointing at the real web UI (not file://).
  ROHOMIEO_PUBLIC_URL="${ROHOMIEO_PUBLIC_URL}" \
  ROHOMIEO_SESSION="${ROHOMIEO_SESSION}" \
  ROHOMIEO_PIN="${ROHOMIEO_PIN}" \
  ROHOMIEO_TURN_URL="${ROHOMIEO_TURN_URL:-}" \
  ROHOMIEO_TURN_USER="${ROHOMIEO_TURN_USER:-}" \
  ROHOMIEO_TURN_PASS="${ROHOMIEO_TURN_PASS:-}" \
  python3 - <<'PY'
import os
from urllib.parse import urlencode, urlparse, urlunparse

base = os.environ["ROHOMIEO_PUBLIC_URL"].rstrip("/")
parts = urlparse(base if "://" in base else f"https://{base}")
q = {
    "s": os.environ["ROHOMIEO_SESSION"],
    "p": os.environ["ROHOMIEO_PIN"],
    "auto": "1",
}
turn = os.environ.get("ROHOMIEO_TURN_URL") or ""
user = os.environ.get("ROHOMIEO_TURN_USER") or ""
pw = os.environ.get("ROHOMIEO_TURN_PASS") or ""
if turn and user and pw:
    ws_scheme = "ws" if parts.scheme == "http" else "wss"
    host = parts.hostname or "127.0.0.1"
    port = parts.port or (80 if parts.scheme == "http" else 443)
    q["ws"] = f"{ws_scheme}://{host}:{port}/ws"
    q["turn"] = turn
    q["turnu"] = user
    q["turnp"] = pw
print(urlunparse((parts.scheme, parts.netloc, "/", "", urlencode(q), "")))
PY
}

if [[ "$MODE" == "local" ]]; then
  LAN_IP="$(upnp_local_ip)"
  LAN_IP="${LAN_IP:-127.0.0.1}"
  export ROHOMIEO_SIGNALING_URL="${WS_SCHEME}://127.0.0.1:${PORT}/ws"
  export ROHOMIEO_PUBLIC_URL="${SCHEME}://${LAN_IP}:${PORT}"
  unset ROHOMIEO_TURN_URL || true
  echo "==> local mode — join URL will use LAN IP ${LAN_IP} (no UPnP / TURN)"
else
  PUBLIC_IP="${ROHOMIEO_PUBLIC_IP:-}"
  if [[ -z "$PUBLIC_IP" ]]; then
    PUBLIC_IP="$(curl -fsS --max-time 5 ifconfig.me 2>/dev/null || true)"
  fi
  if [[ -z "$PUBLIC_IP" ]]; then
    echo "global mode needs a public IP (curl ifconfig.me failed)." >&2
    echo "Set ROHOMIEO_PUBLIC_IP in .env.rohomieo and re-run." >&2
    exit 1
  fi
  export ROHOMIEO_PUBLIC_IP="$PUBLIC_IP"
  # Host dials loopback — WSL/NAT often cannot hairpin back to the public IP.
  # The printed invite still points at the public/WAN address (web UI).
  export ROHOMIEO_SIGNALING_URL="${WS_SCHEME}://127.0.0.1:${PORT}/ws"
  export ROHOMIEO_PUBLIC_URL="${SCHEME}://${PUBLIC_IP}:${PORT}"
  export ROHOMIEO_TURN_URL="turn:${PUBLIC_IP}:3478"
  ensure_turn_creds
  echo "==> global mode — public IP ${PUBLIC_IP} (TURN + UPnP; host dials 127.0.0.1)"
fi

JOIN_URL="$(build_join_url)"
export ROHOMIEO_JOIN_URL="$JOIN_URL"
# Ensure web UI + certs exist for a fresh clone.
if [[ ! -d "$ROOT/web/dist" ]]; then
  echo "==> building web UI"
  (cd "$ROOT/web" && npm ci && npm run build) || (cd "$ROOT/web" && npm install && npm run build)
fi
if [[ ! -f "$ROOT/infra/certs/cert.pem" ]]; then
  echo "==> generating dev TLS certs"
  bash "$ROOT/scripts/gen-dev-cert.sh" || true
fi

# Ensure miniupnpc for --global (best-effort).
if [[ "$MODE" == "global" ]] && ! command -v upnpc >/dev/null; then
  if command -v apt-get >/dev/null; then
    echo "==> installing miniupnpc for UPnP"
    sudo apt-get update -qq && sudo apt-get install -y -qq miniupnpc || true
  elif [[ "$PLATFORM" == "macos" ]]; then
    BREW="$(rohomieo_brew_bin || true)"
    [[ -n "$BREW" ]] && "$BREW" install miniupnpc || true
  fi
fi

PIDS=()
cleanup() {
  echo "==> shutting down"
  for pid in "${PIDS[@]:-}"; do
    kill "$pid" 2>/dev/null || true
  done
  if [[ "$PLATFORM" == "wsl" ]]; then
    if command -v taskkill.exe >/dev/null 2>&1; then
      taskkill.exe /IM rohomieo-host.exe /F >/dev/null 2>&1 || true
      taskkill.exe /IM rohomieo-signaling.exe /F >/dev/null 2>&1 || true
    fi
  fi
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# WSL desktop capture lives on Windows — Windows signaling+host, TURN in WSL.
if [[ "$PLATFORM" == "wsl" ]]; then
  export ROHOMIEO_ROOT="$ROOT"
  # shellcheck disable=SC1091
  source "$ROOT/scripts/lib/setup-common.sh"

  if [[ ! -f "$ROOT/target/release/rohomieo-host.exe" ]]; then
    echo "==> building Windows host/signaling"
    "$ROOT/scripts/build-windows-host.sh" || true
  fi
  "$ROOT/scripts/sync-windows-run.sh" || true

  if [[ "$MODE" == "global" ]]; then
    # Signaling listens on Windows — prefer Windows LAN IP for UPnP mapping.
    WIN_LAN=""
    if setup_powershell_windows_bin &>/dev/null; then
      WIN_LAN=$(setup_ps_windows_command \
        "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.IPAddress -match '^192\.168\.|^10\.' -and \$_.InterfaceAlias -notmatch 'WSL|vEthernet|Loopback' } | Select-Object -First 1).IPAddress" 2>/dev/null \
        | tr -d '\r' || true)
    fi
    upnp_open "$PORT" tcp "signaling" "${WIN_LAN:-}"

    if ss -ulnp 2>/dev/null | grep -q ':3478'; then
      echo "UDP :3478 is already in use — stop the other TURN/coturn session and retry." >&2
      ss -ulnp 2>/dev/null | grep ':3478' | head -3 >&2 || true
      exit 1
    fi

    ./scripts/start-turn.sh &
    turn_pid=$!
    PIDS+=("$turn_pid")
    # Wait until OUR turnserver child is listening (not some other process on :3478).
    turn_ok=false
    for _ in $(seq 1 30); do
      if ! kill -0 "$turn_pid" 2>/dev/null; then
        wait "$turn_pid" 2>/dev/null || true
        echo "TURN failed to start — see messages above." >&2
        exit 1
      fi
      if ss -ulnp 2>/dev/null | grep ':3478' | grep -q "pid=$turn_pid"; then
        turn_ok=true
        break
      fi
      # Some ss builds only show the turnserver pid in the users=() field.
      if ss -ulnp 2>/dev/null | grep ':3478' | grep -q "turnserver" \
        && pgrep -P "$turn_pid" -a 2>/dev/null | grep -q turnserver; then
        turn_ok=true
        break
      fi
      sleep 0.5
    done
    if [[ "$turn_ok" != "true" ]]; then
      echo "TURN did not bind :3478 within 15s." >&2
      exit 1
    fi
    echo "==> TURN listening on :3478"
  fi

  ps_win="$(setup_powershell_windows_bin 2>/dev/null || true)"
  bridge="$ROOT/scripts/windows/run-bridge.ps1"
  bridge_w="$(wslpath -w "$bridge" 2>/dev/null || true)"
  if [[ -n "${ps_win:-}" && -n "${bridge_w:-}" ]]; then
    echo "==> WSL: starting Windows signaling + host"
    ps_args=(-NoProfile -ExecutionPolicy Bypass -File "$bridge_w")
    [[ -n "${ROHOMIEO_PUBLIC_URL:-}" ]] && ps_args+=(-PublicUrl "$ROHOMIEO_PUBLIC_URL")
    [[ -n "${ROHOMIEO_TURN_URL:-}" ]] && ps_args+=(-TurnUrl "$ROHOMIEO_TURN_URL")
    [[ -n "${ROHOMIEO_TURN_USER:-}" ]] && ps_args+=(-TurnUser "$ROHOMIEO_TURN_USER")
    [[ -n "${ROHOMIEO_TURN_PASS:-}" ]] && ps_args+=(-TurnPass "$ROHOMIEO_TURN_PASS")
    [[ -n "${ROHOMIEO_SESSION:-}" ]] && ps_args+=(-Session "$ROHOMIEO_SESSION")
    [[ -n "${ROHOMIEO_PIN:-}" ]] && ps_args+=(-Pin "$ROHOMIEO_PIN")
    "$ps_win" "${ps_args[@]}" &
    PIDS+=($!)
    # Wait briefly for signaling/host, then print the web-UI invite in THIS terminal.
    sleep 4
    ./scripts/print-invite-qr.sh "$JOIN_URL"
    if [[ "$MODE" == "global" ]]; then
      echo "  Forward TCP ${PORT} + UDP/TCP 3478 if UPnP failed."
    fi
    echo "  Ctrl+C stops this session."
    echo ""
    set +e
    wait "${PIDS[@]}"
    ec=$?
    set -e
    exit "$ec"
  fi
  echo "==> WSL: Windows bridge unavailable — falling back to Linux binaries" >&2
fi

./scripts/start-signaling-fg.sh &
PIDS+=($!)
sleep 1
if [[ "$MODE" == "global" ]]; then
  if ss -ulnp 2>/dev/null | grep -q ':3478'; then
    echo "UDP :3478 is already in use — stop the other TURN/coturn session and retry." >&2
    exit 1
  fi
  ./scripts/start-turn.sh &
  turn_pid=$!
  PIDS+=("$turn_pid")
  turn_ok=false
  for _ in $(seq 1 30); do
    if ! kill -0 "$turn_pid" 2>/dev/null; then
      wait "$turn_pid" 2>/dev/null || true
      echo "TURN failed to start — see messages above." >&2
      exit 1
    fi
    if ss -ulnp 2>/dev/null | grep ':3478' | grep -q "turnserver" \
      && pgrep -P "$turn_pid" -a 2>/dev/null | grep -q turnserver; then
      turn_ok=true
      break
    fi
    sleep 0.5
  done
  if [[ "$turn_ok" != "true" ]]; then
    echo "TURN did not bind :3478 within 15s." >&2
    exit 1
  fi
  echo "==> TURN listening on :3478"
fi
./scripts/start-host-fg.sh &
PIDS+=($!)
sleep 2
./scripts/print-invite-qr.sh "$JOIN_URL"
if [[ "$MODE" == "global" ]]; then
  echo "  Forward TCP ${PORT} + UDP/TCP 3478 if UPnP failed."
fi
echo "  Ctrl+C stops this session."
echo ""

if [[ "${BASH_VERSINFO[0]}" -gt 4 ]] \
  || { [[ "${BASH_VERSINFO[0]}" -eq 4 ]] && [[ "${BASH_VERSINFO[1]}" -ge 3 ]]; }; then
  wait -n "${PIDS[@]}"
else
  while true; do
    for pid in "${PIDS[@]}"; do
      if ! kill -0 "$pid" 2>/dev/null; then
        wait "$pid"
        exit $?
      fi
    done
    sleep 0.5
  done
fi
