#!/usr/bin/env bash
# One command to run Rohomieo: ./scripts/run.sh [--local|--global]
# Auto-detects platform (Linux / WSL / macOS), starts signaling + (optional TURN)
# + host as background children of this script, and tears them down on Ctrl-C.
#
# Reachability:
#   --local   (default) same Wi‑Fi / LAN — join URL uses LAN IP, no UPnP/TURN
#   --global  internet — UPnP when possible; otherwise outbound tunnels
#             (cloudflared + bore) so no router port-forwards are required
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib-platform.sh"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib-upnp.sh"

usage() {
  cat <<EOF
usage: $0 [--local|--global]

  --local   LAN only (default). Join URL uses LAN IP. No UPnP / TURN.
  --global  Internet. Tries UPnP; if the router won't open ports, starts
            outbound tunnels (cloudflared + bore) automatically.

Platform is auto-detected (linux / wsl / macos).
EOF
}

MODE="local"
for arg in "$@"; do
  case "$arg" in
    --local) MODE="local" ;;
    --global) MODE="global" ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "unknown argument: $arg" >&2
      usage >&2
      exit 1
      ;;
  esac
done

PLATFORM="$(rohomieo_detect_platform)"
echo "==> platform: $PLATFORM · mode: $MODE"

export PATH="$(rohomieo_tool_path "${HOME:-}")${PATH:+:$PATH}"

[[ -f .env.rohomieo ]] || {
  mkdir -p var/log var/run .local/bin
  cat >.env.rohomieo <<EOF
# Generated by scripts/run.sh — safe to edit
export ROHOMIEO_ROOT="$ROOT"
export ROHOMIEO_BIND="0.0.0.0:8443"
export ROHOMIEO_SIGNALING_URL="wss://127.0.0.1:8443/ws"
export ROHOMIEO_WEB_ROOT="$ROOT/web/dist"
export ROHOMIEO_CERT="$ROOT/infra/certs/cert.pem"
export ROHOMIEO_KEY="$ROOT/infra/certs/key.pem"
EOF
}
# shellcheck disable=SC1091
source .env.rohomieo

# Reachability overrides — must win over .env.rohomieo for this run.
export ROHOMIEO_MODE="$MODE"
PORT="${ROHOMIEO_BIND##*:}"
PORT="${PORT:-8443}"
SCHEME="https"
[[ -f "${ROHOMIEO_CERT:-}" && -f "${ROHOMIEO_KEY:-}" ]] || SCHEME="http"
WS_SCHEME="wss"
[[ "$SCHEME" == "http" ]] && WS_SCHEME="ws"

NEED_TUNNELS=0

ensure_turn_creds() {
  # Fresh TURN secrets every --global run so old invite URLs stop working.
  ROHOMIEO_TURN_USER="rh$(head -c 6 /dev/urandom | xxd -p)"
  ROHOMIEO_TURN_PASS="$(head -c 24 /dev/urandom | xxd -p)"
  export ROHOMIEO_TURN_USER ROHOMIEO_TURN_PASS
  # Do not persist to .env.rohomieo — reused static creds would remain valid forever.
  echo "==> generated session-scoped TURN credentials (not saved to disk)"
}

# Fixed session/PIN for this run so we can print the web-UI invite in this terminal.
export ROHOMIEO_SESSION="${ROHOMIEO_SESSION:-$(python3 -c 'import uuid; print(uuid.uuid4())')}"
if [[ -z "${ROHOMIEO_PIN:-}" ]]; then
  if [[ "$MODE" == "global" ]]; then
    # 8-digit PIN for internet-facing sessions (still lockout-protected by signaling).
    export ROHOMIEO_PIN="$(python3 -c 'import secrets; print(f"{secrets.randbelow(10**8):08d}")')"
  else
    export ROHOMIEO_PIN="$(python3 -c 'import secrets; print(f"{secrets.randbelow(900000) + 100000}")')"
  fi
fi

build_join_url() {
  # Builds https://…/?s=&p=&auto=1… pointing at the real web UI (not file://).
  ROHOMIEO_PUBLIC_URL="${ROHOMIEO_PUBLIC_URL}" \
  ROHOMIEO_SESSION="${ROHOMIEO_SESSION}" \
  ROHOMIEO_PIN="${ROHOMIEO_PIN}" \
  ROHOMIEO_TURN_URL="${ROHOMIEO_TURN_URL:-}" \
  ROHOMIEO_TURN_USER="${ROHOMIEO_TURN_USER:-}" \
  ROHOMIEO_TURN_PASS="${ROHOMIEO_TURN_PASS:-}" \
  python3 - <<'PY'
import os
from urllib.parse import urlencode, urlparse, urlunparse

base = os.environ["ROHOMIEO_PUBLIC_URL"].rstrip("/")
parts = urlparse(base if "://" in base else f"https://{base}")
q = {
    "s": os.environ["ROHOMIEO_SESSION"],
    "p": os.environ["ROHOMIEO_PIN"],
    "auto": "1",
}
turn = os.environ.get("ROHOMIEO_TURN_URL") or ""
user = os.environ.get("ROHOMIEO_TURN_USER") or ""
pw = os.environ.get("ROHOMIEO_TURN_PASS") or ""
if turn and user and pw:
    ws_scheme = "ws" if parts.scheme == "http" else "wss"
    host = parts.hostname or "127.0.0.1"
    port = parts.port
    if port:
        q["ws"] = f"{ws_scheme}://{host}:{port}/ws"
    else:
        q["ws"] = f"{ws_scheme}://{host}/ws"
    q["turn"] = turn
    q["turnu"] = user
    q["turnp"] = pw
print(urlunparse((parts.scheme, parts.netloc, "/", "", urlencode(q), "")))
PY
}

# Returns 0 if router UPnP mapped signaling TCP (and best-effort TURN).
# On WSL/--global always runs enable-upnp.sh first (saved elevated task or one UAC).
rohomieo_try_upnp_global() {
  local lan="${1:-}"
  local ok=0

  if [[ "$PLATFORM" == "wsl" && "${ROHOMIEO_SKIP_UPNP_PREP:-}" != "1" ]]; then
    echo "==> --global: Windows UPnP prep (Private + discovery + maps)"
    # Exit 0 = maps/IGD OK; exit 2 = Windows OK but router still off — keep going.
    set +e
    bash "$ROOT/scripts/enable-upnp.sh"
    local upnp_ec=$?
    set -e
    if [[ "$upnp_ec" -eq 0 ]]; then
      ok=1
    fi
  fi

  # Prefer Windows NATUPnP when available (WSL miniupnpc often can't see the IGD).
  if [[ "$ok" != "1" && "$PLATFORM" == "wsl" ]] && declare -F setup_powershell_windows_bin >/dev/null 2>&1; then
    local ps_win bridge_w
    ps_win="$(setup_powershell_windows_bin 2>/dev/null || true)"
    bridge_w="$(wslpath -w "$ROOT/scripts/windows/open-ports-upnp.ps1" 2>/dev/null || true)"
    if [[ -n "${ps_win:-}" && -n "${bridge_w:-}" ]]; then
      if [[ -n "$lan" ]]; then
        "$ps_win" -NoProfile -ExecutionPolicy Bypass -File "$bridge_w" -LanIp "$lan" && ok=1 || true
      else
        "$ps_win" -NoProfile -ExecutionPolicy Bypass -File "$bridge_w" && ok=1 || true
      fi
    fi
  fi
  if upnp_open "$PORT" tcp "signaling" "${lan:-}"; then
    ok=1
  fi
  upnp_open 3478 udp "turn" "${lan:-}" || true
  upnp_open 3478 tcp "turn" "${lan:-}" || true
  return $((1 - ok))
}

rohomieo_start_tunnels_and_rewrite() {
  local origin="$1"
  # shellcheck disable=SC1090
  eval "$("$ROOT/scripts/start-global-tunnels.sh" "$origin")"
  export ROHOMIEO_PUBLIC_URL ROHOMIEO_TURN_URL
  export ROHOMIEO_REACHABILITY=tunnel
  [[ -n "${CLOUDFLARED_PID:-}" ]] && PIDS+=("$CLOUDFLARED_PID")
  [[ -n "${BORE_PID:-}" ]] && PIDS+=("$BORE_PID")
  JOIN_URL="$(build_join_url)"
  export ROHOMIEO_JOIN_URL="$JOIN_URL"
}

if [[ "$MODE" == "local" ]]; then
  LAN_IP="$(upnp_local_ip)"
  LAN_IP="${LAN_IP:-127.0.0.1}"
  export ROHOMIEO_SIGNALING_URL="${WS_SCHEME}://127.0.0.1:${PORT}/ws"
  export ROHOMIEO_PUBLIC_URL="${SCHEME}://${LAN_IP}:${PORT}"
  unset ROHOMIEO_TURN_URL || true
  echo "==> local mode — join URL will use LAN IP ${LAN_IP} (no UPnP / TURN)"
else
  PUBLIC_IP="${ROHOMIEO_PUBLIC_IP:-}"
  if [[ -z "$PUBLIC_IP" ]]; then
    PUBLIC_IP="$(curl -fsS --max-time 5 ifconfig.me 2>/dev/null || true)"
  fi
  export ROHOMIEO_SIGNALING_URL="${WS_SCHEME}://127.0.0.1:${PORT}/ws"
  ensure_turn_creds
  if [[ -n "$PUBLIC_IP" ]]; then
    export ROHOMIEO_PUBLIC_IP="$PUBLIC_IP"
    # Placeholder invite until UPnP succeeds or tunnels rewrite these.
    export ROHOMIEO_PUBLIC_URL="${SCHEME}://${PUBLIC_IP}:${PORT}"
    export ROHOMIEO_TURN_URL="turn:${PUBLIC_IP}:3478"
    echo "==> global mode — public IP ${PUBLIC_IP} (UPnP, or tunnels if router blocks)"
  else
    NEED_TUNNELS=1
    LAN_IP="$(upnp_local_ip)"
    LAN_IP="${LAN_IP:-127.0.0.1}"
    export ROHOMIEO_PUBLIC_URL="${SCHEME}://${LAN_IP}:${PORT}"
    export ROHOMIEO_TURN_URL="turn:127.0.0.1:3478"
    echo "==> global mode — no public IP detected; will use outbound tunnels"
  fi
fi

JOIN_URL="$(build_join_url)"
export ROHOMIEO_JOIN_URL="$JOIN_URL"
# Ensure web UI + certs exist for a fresh clone.
if [[ ! -d "$ROOT/web/dist" ]]; then
  echo "==> building web UI"
  (cd "$ROOT/web" && npm ci && npm run build) || (cd "$ROOT/web" && npm install && npm run build)
fi
if [[ ! -f "$ROOT/infra/certs/cert.pem" ]]; then
  echo "==> generating dev TLS certs"
  bash "$ROOT/scripts/gen-dev-cert.sh" || true
fi

# Ensure miniupnpc for --global (best-effort).
if [[ "$MODE" == "global" ]] && ! command -v upnpc >/dev/null; then
  if command -v apt-get >/dev/null; then
    echo "==> installing miniupnpc for UPnP"
    sudo apt-get update -qq && sudo apt-get install -y -qq miniupnpc || true
  elif [[ "$PLATFORM" == "macos" ]]; then
    BREW="$(rohomieo_brew_bin || true)"
    [[ -n "$BREW" ]] && "$BREW" install miniupnpc || true
  fi
fi

PIDS=()
cleanup() {
  echo "==> shutting down"
  for pid in "${PIDS[@]:-}"; do
    kill "$pid" 2>/dev/null || true
  done
  if [[ -f "$ROOT/var/run/tunnels.env" ]]; then
    # shellcheck disable=SC1091
    source "$ROOT/var/run/tunnels.env" || true
    [[ -n "${CLOUDFLARED_PID:-}" ]] && kill "$CLOUDFLARED_PID" 2>/dev/null || true
    [[ -n "${BORE_PID:-}" ]] && kill "$BORE_PID" 2>/dev/null || true
    rm -f "$ROOT/var/run/tunnels.env"
  fi
  if [[ "$PLATFORM" == "wsl" ]]; then
    if command -v taskkill.exe >/dev/null 2>&1; then
      taskkill.exe /IM rohomieo-host.exe /F >/dev/null 2>&1 || true
      taskkill.exe /IM rohomieo-signaling.exe /F >/dev/null 2>&1 || true
    fi
  fi
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

wait_for_our_turn() {
  local turn_pid="$1"
  local turn_ok=false
  for _ in $(seq 1 40); do
    if ! kill -0 "$turn_pid" 2>/dev/null; then
      wait "$turn_pid" 2>/dev/null || true
      echo "TURN failed to start — see messages above." >&2
      exit 1
    fi
    # start-turn.sh exec's turnserver (same PID) or keeps it as a child.
    if ss -ulnp 2>/dev/null | grep ':3478' | grep -q "turnserver"; then
      if grep -q turnserver "/proc/$turn_pid/comm" 2>/dev/null \
        || pgrep -P "$turn_pid" -a 2>/dev/null | grep -q turnserver \
        || ss -ulnp 2>/dev/null | grep ':3478' | grep -q "pid=$turn_pid"; then
        turn_ok=true
        break
      fi
    fi
    sleep 0.5
  done
  if [[ "$turn_ok" != "true" ]]; then
    echo "TURN did not bind :3478 within 20s." >&2
    exit 1
  fi
  echo "==> TURN listening on :3478"
}

# WSL desktop capture lives on Windows — Windows signaling+host, TURN in WSL.
if [[ "$PLATFORM" == "wsl" ]]; then
  export ROHOMIEO_ROOT="$ROOT"
  # shellcheck disable=SC1091
  source "$ROOT/scripts/lib/setup-common.sh"

  if [[ ! -f "$ROOT/target/release/rohomieo-host.exe" ]]; then
    echo "==> building Windows host/signaling"
    "$ROOT/scripts/build-windows-host.sh" || true
  fi
  "$ROOT/scripts/sync-windows-run.sh" || true

  WIN_LAN=""
  if setup_powershell_windows_bin &>/dev/null; then
    WIN_LAN=$(setup_ps_windows_command \
      "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.IPAddress -match '^192\.168\.|^10\.' -and \$_.InterfaceAlias -notmatch 'WSL|vEthernet|Loopback' } | Select-Object -First 1).IPAddress" 2>/dev/null \
      | tr -d '\r' || true)
  fi
  export WIN_LAN

  if [[ "$MODE" == "global" ]]; then
    # Always run Windows UPnP prep on --global (saved task or one UAC).
    if ! rohomieo_try_upnp_global "${WIN_LAN:-}"; then
      echo "==> router UPnP could not open ports — will use outbound tunnels after signaling is up"
      NEED_TUNNELS=1
    else
      echo "==> UPnP OK — using public IP ${ROHOMIEO_PUBLIC_IP:-tunnel-fallback} for invite"
      # If we have no public IP, still need tunnels even when local IGD mapped oddly.
      if [[ -z "${ROHOMIEO_PUBLIC_IP:-}" ]]; then
        NEED_TUNNELS=1
      fi
    fi

    if ss -ulnp 2>/dev/null | grep -q ':3478'; then
      echo "UDP :3478 is already in use — stop the other TURN/coturn session and retry." >&2
      ss -ulnp 2>/dev/null | grep ':3478' | head -3 >&2 || true
      exit 1
    fi

    if [[ "$NEED_TUNNELS" == "1" ]]; then
      export ROHOMIEO_SKIP_UPNP=1
    fi
    ./scripts/start-turn.sh &
    turn_pid=$!
    PIDS+=("$turn_pid")
    wait_for_our_turn "$turn_pid"
  fi

  ps_win="$(setup_powershell_windows_bin 2>/dev/null || true)"
  bridge="$ROOT/scripts/windows/run-bridge.ps1"
  bridge_w="$(wslpath -w "$bridge" 2>/dev/null || true)"
  if [[ -n "${ps_win:-}" && -n "${bridge_w:-}" ]]; then
    echo "==> WSL: starting Windows signaling + host"
    ps_args=(-NoProfile -ExecutionPolicy Bypass -File "$bridge_w")
    [[ -n "${ROHOMIEO_PUBLIC_URL:-}" ]] && ps_args+=(-PublicUrl "$ROHOMIEO_PUBLIC_URL")
    [[ -n "${ROHOMIEO_TURN_URL:-}" ]] && ps_args+=(-TurnUrl "$ROHOMIEO_TURN_URL")
    [[ -n "${ROHOMIEO_TURN_USER:-}" ]] && ps_args+=(-TurnUser "$ROHOMIEO_TURN_USER")
    [[ -n "${ROHOMIEO_TURN_PASS:-}" ]] && ps_args+=(-TurnPass "$ROHOMIEO_TURN_PASS")
    [[ -n "${ROHOMIEO_SESSION:-}" ]] && ps_args+=(-Session "$ROHOMIEO_SESSION")
    [[ -n "${ROHOMIEO_PIN:-}" ]] && ps_args+=(-Pin "$ROHOMIEO_PIN")
    if [[ -n "${ROHOMIEO_ADMIN_TOKEN:-}" ]]; then
      ps_args+=(-AdminToken "$ROHOMIEO_ADMIN_TOKEN")
    elif [[ "$MODE" == "local" || "${ROHOMIEO_EXPOSE_ADMIN_API:-}" == "1" ]]; then
      ps_args+=(-ExposeAdminApi)
    fi
    "$ps_win" "${ps_args[@]}" &
    PIDS+=($!)
    sleep 5

    if [[ "$MODE" == "global" && "$NEED_TUNNELS" == "1" ]]; then
      ORIGIN="${SCHEME}://${WIN_LAN:-127.0.0.1}:${PORT}"
      rohomieo_start_tunnels_and_rewrite "$ORIGIN"
      restart_w="$(wslpath -w "$ROOT/scripts/windows/restart-host.ps1" 2>/dev/null || true)"
      if [[ -n "$restart_w" ]]; then
        echo "==> restarting Windows host with tunnel invite"
        "$ps_win" -NoProfile -ExecutionPolicy Bypass -File "$restart_w" \
          -PublicUrl "$ROHOMIEO_PUBLIC_URL" \
          -TurnUrl "$ROHOMIEO_TURN_URL" \
          -TurnUser "$ROHOMIEO_TURN_USER" \
          -TurnPass "$ROHOMIEO_TURN_PASS" \
          -Session "$ROHOMIEO_SESSION" \
          -Pin "$ROHOMIEO_PIN" || true
        sleep 2
      fi
    fi

    ./scripts/print-invite-qr.sh "$JOIN_URL"
    if [[ "${ROHOMIEO_REACHABILITY:-}" == "tunnel" ]]; then
      echo "  Reachability: outbound tunnels (no router ports)."
    fi
    echo "  Ctrl+C stops this session (and tunnels)."
    echo ""
    set +e
    wait "${PIDS[@]}"
    ec=$?
    set -e
    exit "$ec"
  fi
  echo "==> WSL: Windows bridge unavailable — falling back to Linux binaries" >&2
fi

./scripts/start-signaling-fg.sh &
PIDS+=($!)
sleep 1
if [[ "$MODE" == "global" ]]; then
  if ! rohomieo_try_upnp_global; then
    echo "==> router UPnP could not open ports — will use outbound tunnels"
    NEED_TUNNELS=1
  else
    echo "==> UPnP OK — using public IP ${ROHOMIEO_PUBLIC_IP:-} for invite"
    if [[ -z "${ROHOMIEO_PUBLIC_IP:-}" ]]; then
      NEED_TUNNELS=1
    fi
  fi
  if ss -ulnp 2>/dev/null | grep -q ':3478'; then
    echo "UDP :3478 is already in use — stop the other TURN/coturn session and retry." >&2
    exit 1
  fi
  if [[ "$NEED_TUNNELS" == "1" ]]; then
    export ROHOMIEO_SKIP_UPNP=1
  fi
  ./scripts/start-turn.sh &
  turn_pid=$!
  PIDS+=("$turn_pid")
  wait_for_our_turn "$turn_pid"
fi
./scripts/start-host-fg.sh &
PIDS+=($!)
sleep 2

if [[ "$MODE" == "global" && "$NEED_TUNNELS" == "1" ]]; then
  ORIGIN="${SCHEME}://127.0.0.1:${PORT}"
  rohomieo_start_tunnels_and_rewrite "$ORIGIN"
  # Restart Linux host so its QR matches the tunnel invite.
  for pid in "${PIDS[@]}"; do
    if kill -0 "$pid" 2>/dev/null && tr '\0' ' ' <"/proc/$pid/cmdline" 2>/dev/null | grep -q 'rohomieo-host\|start-host'; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  sleep 1
  ./scripts/start-host-fg.sh &
  PIDS+=($!)
  sleep 2
fi

./scripts/print-invite-qr.sh "$JOIN_URL"
if [[ "${ROHOMIEO_REACHABILITY:-}" == "tunnel" ]]; then
  echo "  Reachability: outbound tunnels (no router ports)."
fi
echo "  Ctrl+C stops this session."
echo ""

if [[ "${BASH_VERSINFO[0]}" -gt 4 ]] \
  || { [[ "${BASH_VERSINFO[0]}" -eq 4 ]] && [[ "${BASH_VERSINFO[1]}" -ge 3 ]]; }; then
  wait -n "${PIDS[@]}"
else
  while true; do
    for pid in "${PIDS[@]}"; do
      if ! kill -0 "$pid" 2>/dev/null; then
        wait "$pid"
        exit $?
      fi
    done
    sleep 0.5
  done
fi
