# Rohomieo Windows setup — Rust, Node, build host+signaling, optional scheduled tasks.
param(
    [string]$RepoRoot = "",
    [switch]$InstallService,
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}
$RepoRoot = (Resolve-Path $RepoRoot).Path

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "OK  $msg" -ForegroundColor Green }

Write-Step "Rohomieo Windows setup — $RepoRoot"

# Rust
if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
    Write-Step "Installing Rust (rustup)..."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile "$env:TEMP\rustup-init.exe"
    & "$env:TEMP\rustup-init.exe" -y --default-toolchain stable
    $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"
}
Write-Ok "Rust: $(rustc --version)"

# Node.js
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Step "Installing Node.js LTS via winget..."
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        winget install OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                    [System.Environment]::GetEnvironmentVariable("Path", "User")
    } else {
        Write-Warning "Install Node.js from https://nodejs.org/ then re-run setup"
    }
}
if (Get-Command node -ErrorAction SilentlyContinue) {
    Write-Ok "Node: $(node --version)"
}

# OpenSSL for tooling (optional, signaling uses rustls)
if (Get-Command winget -ErrorAction SilentlyContinue) {
    winget install ShiningLight.OpenSSL.Light --accept-package-agreements --accept-source-agreements 2>$null
}

Set-Location $RepoRoot

# Web build
if (-not $SkipBuild) {
    Write-Step "Building web PWA..."
    Push-Location (Join-Path $RepoRoot "web")
    npm ci
    npm run build
    Pop-Location
    Write-Ok "web/dist"

    Write-Step "Building Rust (release)..."
    cargo build --release -p rohomieo-signaling
    cargo build --release -p rohomieo-host
    Write-Ok "target/release binaries"
}

# Dev TLS cert (Git Bash openssl or Windows openssl)
$certDir = Join-Path $RepoRoot "infra\certs"
if (-not (Test-Path (Join-Path $certDir "cert.pem"))) {
    New-Item -ItemType Directory -Force -Path $certDir | Out-Null
    $openssl = Get-Command openssl -ErrorAction SilentlyContinue
    if ($openssl) {
        Write-Step "Generating dev TLS certificate..."
        & openssl req -x509 -newkey rsa:4096 -sha256 -days 825 -nodes `
            -keyout (Join-Path $certDir "key.pem") `
            -out (Join-Path $certDir "cert.pem") `
            -subj "/CN=rohomieo.local" `
            -addext "subjectAltName=DNS:rohomieo.local,IP:127.0.0.1"
        Write-Ok "infra/certs"
    }
}

# Windows env file
$envFile = Join-Path $RepoRoot ".env.rohomieo.windows"
@"
# Generated by setup-windows.ps1
ROHOMIEO_ROOT=$RepoRoot
ROHOMIEO_BIND=0.0.0.0:8443
ROHOMIEO_SIGNALING_URL=ws://127.0.0.1:8443/ws
ROHOMIEO_WEB_ROOT=$RepoRoot\web\dist
ROHOMIEO_CERT=$RepoRoot\infra\certs\cert.pem
ROHOMIEO_KEY=$RepoRoot\infra\certs\key.pem
"@ | Set-Content -Encoding UTF8 $envFile
Write-Ok ".env.rohomieo.windows"

# Launcher scripts
$launchDir = Join-Path $RepoRoot "scripts\windows"
New-Item -ItemType Directory -Force -Path $launchDir | Out-Null

@'
$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"
Set-Location $root
& "$root\target\release\rohomieo-signaling.exe" --bind 0.0.0.0:8443 --web-root "$root\web\dist"
'@ | Set-Content (Join-Path $launchDir "start-signaling.ps1")

@'
$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"
Set-Location $root
& "$root\target\release\rohomieo-host.exe" --signaling ws://127.0.0.1:8443/ws
'@ | Set-Content (Join-Path $launchDir "start-host.ps1")

@'
# Start both signaling and host (run as Administrator if binding fails)
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Start-Process powershell -ArgumentList "-NoExit","-File","$root\scripts\windows\start-signaling.ps1"
Start-Sleep -Seconds 2
Start-Process powershell -ArgumentList "-NoExit","-File","$root\scripts\windows\start-host.ps1"
Write-Host "Open http://127.0.0.1:8443 — use Session ID + PIN from host window"
'@ | Set-Content (Join-Path $RepoRoot "scripts\start-windows-host.ps1")

Write-Ok "scripts/windows/start-*.ps1"

# Optional: logon scheduled tasks
if ($InstallService) {
    Write-Step "Registering logon scheduled tasks..."
    $sig = Join-Path $RepoRoot "scripts\windows\start-signaling.ps1"
    $host = Join-Path $RepoRoot "scripts\windows\start-host.ps1"
    schtasks /Create /TN "RohomieoSignaling" /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$sig`"" `
        /SC ONLOGON /RL LIMITED /F 2>$null
    schtasks /Create /TN "RohomieoHost" /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$host`"" `
        /SC ONLOGON /RL HIGHEST /F 2>$null
    Write-Ok "Scheduled tasks RohomieoSignaling, RohomieoHost"
}

Write-Host ""
Write-Host "Windows setup complete." -ForegroundColor Green
Write-Host "  Signaling: powershell -File scripts\windows\start-signaling.ps1"
Write-Host "  Host:      powershell -File scripts\windows\start-host.ps1"
Write-Host "  Both:      powershell -File scripts\start-windows-host.ps1"
Write-Host "  Service:   re-run with -InstallService"
Write-Host ""
