# Rohomieo Windows setup - Rust, Node, build host+signaling
param(
    [string]$RepoRoot = "",
    [switch]$InstallService,
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}
$RepoRoot = (Resolve-Path $RepoRoot).Path

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "OK  $msg" -ForegroundColor Green }

Write-Step "Rohomieo Windows setup at $RepoRoot"

if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
    Write-Step "Installing Rust (rustup)..."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile "$env:TEMP\rustup-init.exe"
    & "$env:TEMP\rustup-init.exe" -y --default-toolchain stable
    $env:Path = "$env:USERPROFILE\.cargo\bin;" + $env:Path
}
Write-Ok ("Rust: " + (rustc --version))

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Step "Installing Node.js LTS via winget..."
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        winget install OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
    } else {
        Write-Warning "Install Node.js from https://nodejs.org/ then re-run setup"
    }
}
if (Get-Command node -ErrorAction SilentlyContinue) {
    Write-Ok ("Node: " + (node --version))
}

Set-Location $RepoRoot

# WireGuard for Windows (VPN server on laptop — phone connects remotely)
if (-not $env:ROHOMIEO_SKIP_WIREGUARD) {
    Write-Step "WireGuard for Windows..."
    $wgExe = "${env:ProgramFiles}\WireGuard\wireguard.exe"
    if (Test-Path $wgExe) {
        Write-Ok "WireGuard already installed"
    } elseif (Get-Command winget -ErrorAction SilentlyContinue) {
        winget install --id WireGuard.WireGuard -e --accept-package-agreements --accept-source-agreements 2>$null
        Write-Ok "WireGuard installed (or already present)"
    } else {
        Write-Warning "Install from https://www.wireguard.com/install/"
    }
    if (Get-Command wsl -ErrorAction SilentlyContinue) {
        $wslRepo = (wsl wslpath -u "`"$RepoRoot`"").Trim()
        wsl -e bash -lc "cd '$wslRepo' && ./scripts/wireguard-gen-keys.sh" 2>$null
    }
} else {
    Write-Warning "Skipped WireGuard (ROHOMIEO_SKIP_WIREGUARD=1)"
}

if (-not $SkipBuild) {
    Write-Step "Building web PWA..."
    Push-Location (Join-Path $RepoRoot "web")
    npm ci
    npm run build
    Pop-Location
    Write-Ok "web/dist"

    Write-Step "Building Rust (release, MSVC env)..."
    $buildMsvc = Join-Path $RepoRoot "scripts\windows\build-msvc.ps1"
    & $buildMsvc -RepoRoot $RepoRoot
    Write-Ok "target/release binaries"
}

$certDir = Join-Path $RepoRoot "infra\certs"
if (-not (Test-Path (Join-Path $certDir "cert.pem"))) {
    New-Item -ItemType Directory -Force -Path $certDir | Out-Null
    $openssl = Get-Command openssl -ErrorAction SilentlyContinue
    if ($openssl) {
        Write-Step "Generating dev TLS certificate..."
        & openssl req -x509 -newkey rsa:4096 -sha256 -days 825 -nodes -keyout (Join-Path $certDir "key.pem") -out (Join-Path $certDir "cert.pem") -subj "/CN=rohomieo.local"
        Write-Ok "infra/certs"
    }
}

$envFile = Join-Path $RepoRoot ".env.rohomieo.windows"
$envLines = @(
    "# Generated by setup-windows.ps1",
    "ROHOMIEO_ROOT=$RepoRoot",
    "ROHOMIEO_BIND=0.0.0.0:8443",
    "ROHOMIEO_SIGNALING_URL=ws://127.0.0.1:8443/ws",
    "ROHOMIEO_WEB_ROOT=$RepoRoot\web\dist"
)
$envLines | Set-Content -Encoding UTF8 $envFile
Write-Ok ".env.rohomieo.windows"

if ($InstallService) {
    Write-Step "Registering logon scheduled tasks..."
    $sig = Join-Path $RepoRoot "scripts\windows\start-signaling.ps1"
    $hostScript = Join-Path $RepoRoot "scripts\windows\start-host.ps1"
    schtasks /Create /TN "RohomieoSignaling" /TR ("powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"" + $sig + "`"") /SC ONLOGON /RL LIMITED /F 2>$null
    schtasks /Create /TN "RohomieoHost" /TR ("powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"" + $hostScript + "`"") /SC ONLOGON /RL HIGHEST /F 2>$null
    Write-Ok "Scheduled tasks RohomieoSignaling, RohomieoHost"
}

Write-Host ""
Write-Host "Windows setup complete." -ForegroundColor Green
Write-Host "  Both:  powershell -File scripts\start-windows-host.ps1"
Write-Host ""
